---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sklearn
  namespace: odh-demo
spec:
  name: wine-quality
  predictors: 
  - componentSpecs:
    graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: s3://mlflow-obc-3b2f7dae-20cb-48d9-8b7f-35749480b082/0/17c7086faed64b96b9264f59e5164f4e/artifacts/model
      envSecretRefName: seldon-init-container-secret
      name: classifier
    name: default
    replicas: 1
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: classifier
  namespace: odh-demo  
spec:
  to:
    kind: Service
    name: sklearn-default-classifier
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None